config/routes.rb
Asterism2::Application.routes.draw do
  devise_for :users
  resources :user, :controller => "user"

  root to: 'static_pages#home'

  get '/product_status', to: 'static_pages#product_status'

  get '/about_us', to: 'static_pages#about_us'

  get '/all_users', to: 'static_pages#all_users'

  get '/command_center', to: 'static_pages#command_center'

  get '/contact', to: 'static_pages#contact'

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/bryanrite/cancancan/wiki/Defining-Abilities


    user ||= User.new # guest user (not logged in)
    if user.admin? or user.employee?
      can :manage, :all
    else
      can :read, :all
    end
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :company, presence: true
  validates :office_location, presence: true
  validates :office_country, presence: true
  validates :office_city, presence: true


  def admin?
    admin
  end

  def employee?
    employee
  end
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	before_filter :configure_permitted_parameters, if: :devise_controller?


  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  # Redirect to product_status_path after user signs in
  def after_sign_in_path_for user
    if current_user.admin? or current_user.employee?
      command_center_path
    else
      product_status_path
    end
  end

  # Configure attributes that users may access in order to sign up or update their account.
  # These permitted parameters are required for Devise authentication when using with Rails 4 app.
  def configure_permitted_parameters
  	devise_parameter_sanitizer.for(:sign_up) << :first_name << :last_name << :office_location << :office_country << :office_city << :company
  	devise_parameter_sanitizer.for(:account_update) << :first_name << :last_name << :office_location << :office_country << :office_city << :company
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
	before_filter :authenticate_user!, only: [:product_status]
	require 'open-uri'


	
	def home
	end

	def product_status
		@alldonet_product_list = JSON.load(open('https://trm-dot-alldonetutils.appspot.com/c/asterism/prodlist/?u=asterismui&pw=foobar'))
		@product_list_count = @alldonet_product_list.count
		alldonet_current_user_prod = JSON.load(open("https://trm-dot-alldonetutils.appspot.com/c/asterism/revokeuser/?aid=#{current_user.id}&pk=none&u=asterismui&pw=foobar"))
		@product_desc_part_1 = "https://trm-dot-alldonetutils.appspot.com/c/asterism/getprod/?pk="
		@product_desc_part_2 = "&u=asterismui&pw=foobar"
		@approved_prod = []
		if !alldonet_current_user_prod['urls'].nil?
			alldonet_current_user_prod['urls'].each do |url|
				@approved_prod << url.gsub("=", " ").split.last.to_i
			end
		end
	end

	def about_us
	end

	def all_users
		@users = User.all
		unless current_user.admin? or current_user.employee?
			redirect_to root_path
			flash[:error] = 'You do not have the proper permission level to view that page'
		end
	end

	def command_center
		@alldonet_product_list = JSON.load(open('https://trm-dot-alldonetutils.appspot.com/c/asterism/prodlist/?u=asterismui&pw=foobar'))
		@users = User.all
		unless current_user.admin? or current_user.employee?
			redirect_to root_path
			flash[:error] = 'You do not have the proper permission level to view that page'
		end
	end

	def contact
	end
		
end

app/controllers/user_controller.rb
class UserController < ApplicationController
  load_and_authorize_resource
   
  def index
    @users = User.excludes(:id => current_user.id)
  end
   
  def new
    @user = User.new
  end	   
  def create
    @user = User.new(params[:user])
    if @user.save
      flash[:notice] = "Successfully created User."
      redirect_to root_path
    else
      render :action => 'new'
    end
  end
   
  def edit
    @user = User.find(params[:id])
  end
   
  def update
    @user = User.find(params[:id])
    params[:user].delete(:password) if params[:user][:password].blank?
    params[:user].delete(:password_confirmation) if params[:user][:password].blank? and params[:user][:password_confirmation].blank?
    if @user.update_attributes(update_params)
      flash[:notice] = "Successfully updated User."
      redirect_to all_users_path
    else
      render :action => 'edit'
    end
  end
   
  def destroy
    @user = User.find(params[:id])
    if @user.destroy
      flash[:notice] = "Successfully deleted User."
      redirect_to root_path
    end
  end

  private
   
  def update_params #permitted parameters for update action. This is required for rails 4's Strong Parameter feature 
    params.require(:user).permit(:company, :email, :first_name, :last_name, :office_location, :office_city, :office_country, :employee, :customer, :admin) 
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper

	def concept_icon
		image_tag("concept72.png", class: "table_icon", alt: "concept icon")
	end

	def negotiate_icon
		image_tag("negotiate72.png", class: "table_icon", alt: "negotiating icon")
	end

	def agreement_icon
		image_tag("agreement72.png", class: "table_icon", alt: "agreement icon")
	end

	def review_icon
		image_tag("regulatory_review72.png", class: "table_icon", alt: "regulatory review icon")
	end

	def formulate_icon
		image_tag("formulation72.png", class: "table_icon", alt: "formulation icon")
	end

	def sample_icon
		image_tag("sampling72.png", class: "table_icon", alt: "sampling icon")
	end

	def register_icon
		image_tag("registration72.png", class: "table_icon", alt: "registration icon")
	end

	def manufacture_icon
		image_tag("production72.png", class: "table_icon", alt: "production icon")
	end

	def logistics_icon
		image_tag("logistics72.png", class: "table_icon", alt: "logistics icon")
	end

	def design_icon
		image_tag("design72.png", class: "table_icon", alt: "design icon")
	end

	def print_icon
		image_tag("printing72.png", class: "table_icon", alt: "print icon")
	end

	def procure_icon
		image_tag("ingredients72.png", class: "table_icon", alt: "procure icon")
	end

	def purchaseorder_icon
		image_tag("purchaseorder72.png", class: "table_icon", alt: "purchase order icon")
	end

	def sample_contract_pic
		image_tag("sample_contract.png", class: "oversize_png", alt: "sample contract picture")
	end

	def demo_age_pic
		image_tag("demo_age.jpg", class: "oversize_png", alt: "demo age picture")
	end

	def symbolize_keys_deep!(h)
    h.keys.each do |k|
        ks    = k.respond_to?(:to_sym) ? k.to_sym : k
        h[ks] = h.delete k # Preserve order even when k == ks
        symbolize_keys_deep! h[ks] if h[ks].kind_of? Hash
    end
	end

	# This symbolizes even hashes inside an array.
	def recursive_symbolize_keys!
    symbolize_keys!
    # symbolize each hash in .values
    values.each{|h| h.recursive_symbolize_keys! if h.is_a?(Hash) }
    # symbolize each hash inside an array in .values
    values.select{|v| v.is_a?(Array) }.flatten.each{|h| h.recursive_symbolize_keys! if h.is_a?(Hash) }
    self
  end

	def product_name
		@alldonet_product_list.each do |product|
			product[0..@product_list_count]['pn']
		end
	end
end

app/views/layouts/_footer.html.erb
<footer class="footer col-md-12">
	<small>
		Copyright Asterism Healthcare Plus, inc. 2014<br/>
		Web portal developed by Philip Q Nguyen using RoR
	</small>
	<nav>
		<ul>
			<li><%= link_to "About", about_us_path %>
			</li>
			<li><%= link_to "Contact", contact_path %>
			</li>
		</ul>
	</nav>
	<%= render '/layouts/scripts/javascripts.html.erb' %>
</footer>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default" role="navigation">
  <div class="container">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/">Asterism Healthcare Plus</a>
    </div>

    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to 'About us', about_us_path %></li>
        <li><%= link_to 'Contact', contact_path %></li>
        <% if user_signed_in? %>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">My account<b class="caret"></b></a>
            <ul class="dropdown-menu">
              <li><%= link_to 'Command center', command_center_path if current_user.employee? or current_user.admin? %></li>
              <li><%= link_to 'Product status', product_status_path %></li>
              <li><%= link_to 'Edit my account', edit_user_registration_path %></li>
              <li><%= link_to 'User list', all_users_path if current_user.employee? or current_user.admin? %></li>
              <li class="divider"></li>
              <li><%= link_to 'Sign out', destroy_user_session_path, method: :delete %></li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to 'Sign in / Sign up', new_user_session_path %></li>
        <% end %>
      </ul>
    </div>
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
	<head>
	  <title>Asterism</title>
	  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
	  <%= stylesheet_link_tag 	 "application", "http://fonts.googleapis.com/css?family=Nunito:300" %>
	  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
	  <%= csrf_meta_tags %>
	  <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
	  <meta http-equiv="X-UA-Compatible" content="IE=10; IE=9; IE=8; IE=7; IE=EDGE" />
	</head>
	<body>
		<%= render 'layouts/header' %>
		<div class="container" %>
			<% flash.each do |name, msg| %>
				<%= content_tag(:div, msg, class: "alert alert-#{name}") %>
			<% end %>
			<%= yield %>
			<%= render 'layouts/footer' %>
		</div>

	</body>
</html>

app/views/layouts/scripts/_javascripts.html.erb
<%# Make table heads fixed to top of browser%>
<script>
	$("table.table").floatThead()
</script>


<script>
	$("#collapsible_side_panel").click(function(){
	  $("#main_table").toggleClass("col-md-10");
	}); 
</script>


<%# Script to copy item attributes from dropdown to modal_add_item %>
<script>
  edit = function(pk, p, a, pn) {
      /* initialise the input form based on function parameters */
      $("#pk").prop("value", pk);
      $("#p").prop("value", p);
      $("#a").prop("value", a);
      $("#itemModalLabel").html("Product: " + pn);
      $("#path_item_modal_body").html("Path: " + p);
      $("#v").prop("value", "");
  }
</script>

<%# Script to copy item attributes from dropdown to modal_add_value %>
<script>
  edit_value = function(pk, p, a, pn, cv, item) {
      /* initialise the input form based on function parameters */
      $("#pk2").prop("value", pk);
      $("#p2").prop("value", p);
      $("#a2").prop("value", a);
      $("#valueModalLabel").html("Product: " + pn);
      $("#path_value_modal_body").html("Path: " + p);
      $("#item_value_modal_body").html("Item: " + item);
      $("#v2").prop("value", cv);
  }
</script>

<%# Script to add new item %>
<script>
  function log(text)
  {
      $("#log").append("<li>" + text + "</li>");
  }

  $(document).ready(function() {
      $("#submit_modal_add_item").on('click', function() {
          log("make request");
          $.ajax({
              type: "get",
              url: "https://trm-dot-alldonetutils.appspot.com/c/asterism/setprodinfo/",
              data: {
                  u: "asterismui",
                  pw: "foobar",
                  pk: $("#pk").val(),
                  p: $("#p").val() + '.' + $("#i").val(),
                  a: $("#a").val(),
                  v: $("#v").val()
              },
              dataType: "text",
              crossDomain: true,
              success: function (data) {
                  log("success");
                  $("#result").html(data);
              }
          });
      });
  });
</script>

<%# Script to add/edit value of existing item %>
<script>
  function log(text)
  {
      $("#log").append("<li>" + text + "</li>");
  }

  $(document).ready(function() {
      $("#submit_modal_add_value").on('click', function() {
          log("make request");
          $.ajax({
              type: "get",
              url: "https://trm-dot-alldonetutils.appspot.com/c/asterism/setprodinfo/",
              data: {
                  u: "asterismui",
                  pw: "foobar",
                  pk: $("#pk2").val(),
                  p: $("#p2").val(),
                  a: $("#a2").val(),
                  v: $("#v2").val()
              },
              dataType: "text",
              crossDomain: true,
              success: function (data) {
                  log("success");
                  $("#result").html(data);
              }
          });
      });
  });
</script>


<%# script to delete item %>
<script>
  function log(text)
  {
      $("#log").append("<li>" + text + "</li>");
  }

  $(document).ready(function() {
      $("#delete_item").on('click', function() {
          log("make request");
          $.ajax({
              type: "get",
              url: "https://trm-dot-alldonetutils.appspot.com/c/asterism/delprodinfo/",
              data: {
                  u: "asterismui",
                  pw: "foobar",
                  pk: $("#pk2").val(),
                  p: $("#p2").val(),
                  a: $("#a2").val()
              },
              dataType: "text",
              crossDomain: true,
              success: function (data) {
                  log("success");
                  $("#result").html(data);
              }
          });
      });
  });
</script>


<%# Script to add new product %>
<script>
  function log(text)
  {
      $("#log").append("<li>" + text + "</li>");
  }

  $(document).ready(function() {
      $("#submit_pn").on('click', function() {
          log("make request");
          $.ajax({
              type: "get",
              url: "https://trm-dot-alldonetutils.appspot.com/c/asterism/addprod/",
              data: {
                  u: "asterismui",
                  pw: "foobar",
                  pn: $("#new_pn").val(),
                  a: $("#new_a").val()
              },
              dataType: "text",
              crossDomain: true,
              success: function (data) {
                  log("success");
                  $("#result").html(data);
              }
          });
      });
  });
</script>

<%# Script to assign product to user %>
<script>
  function log(text)
  {
      $("#log").append("<li>" + text + "</li>");
  }

  $(document).ready(function() {
      $("#submit_grant").on('click', function() {
          log("make request");
          $.ajax({
              type: "get",
              url: "https://trm-dot-alldonetutils.appspot.com/c/asterism/grantuser/",
              data: {
                  u: "asterismui",
                  pw: "foobar",
                  pk: $("#grant_pk").val(),
                  aid: $("#grant_aid").val()
              },
              dataType: "text",
              crossDomain: true,
              success: function (data) {
                  log("success");
                  $("#result").html(data);
              }
          });
      });
  });
</script>

<%# Script to remove product from user %>
<script>
  function log(text)
  {
      $("#log").append("<li>" + text + "</li>");
  }

  $(document).ready(function() {
      $("#submit_revoke").on('click', function() {
          log("make request");
          $.ajax({
              type: "get",
              url: "https://trm-dot-alldonetutils.appspot.com/c/asterism/revokeuser/",
              data: {
                  u: "asterismui",
                  pw: "foobar",
                  pk: $("#grant_pk").val(),
                  aid: $("#grant_aid").val()
              },
              dataType: "text",
              crossDomain: true,
              success: function (data) {
                  log("success");
                  $("#result").html(data);
              }
          });
      });
  });
</script>

app/views/static_pages/_small_product_list.html.erb
      	<div class="table-height">
				  <table class="table table-striped">

				    <%########## Begin table headings #####################%>
				    <thead>
				      <tr>
				        <th class="text-center">Product Key</th>
				        <th class="text-center">Product Name</th>
				      </tr>
				    </thead>

				    <%########### Begin table cells in rows ###########%>
				    <% @alldonet_product_list.each do |product| %>
				      <tr>
				  			<ul>
				          <td class="text-center"><%= product['pk'] %></td>
									<td class="text-center"><%= product['pn'] %></td>
				  			</ul>
				  		</tr>
				    <% end %>
					</table>
				</div>

app/views/static_pages/_small_user_list.html.erb
<div class="table-height">
  <table class="table table-striped">

    <%########## Begin table headings #####################%>
    <thead>
      <tr>
        <th class="text-center">User ID</th>
        <th class="text-center">Last, First</th>
        <th class="text-center">Company</th>
      </tr>
    </thead>

    <%########### Begin table cells in rows ###########%>
    <% @users.each do |user| %> 
      <tr>
  			<ul>
          <td class="text-center"><%= user.id %></td>
					<td class="text-center"><%= user.last_name + ", " + user.first_name %></td>
					<td class="text-center"><%= user.company %></td>
  			</ul>
  		</tr>
    <% end %>
	</table>
</div>

app/views/static_pages/about_us.html.erb
<h1>About Us</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3 well well-lg">
		<p>
		ASTERiSM Healthcare Plus, Inc. provides full OEM formulation, herbal compounding and manufacturing solutions of Made in Japan beauty and healthcare products in addition to our proprietary Kinbi product line.
		</p>

		<p>
		Our product range includes high quality functional foods, health beverages, soft drinks, nutraceuticals, etc. We do OEM product development and contract manufacturing (e.g. collagen drinks, energy drinks, slimming products, supplements) in Japan to meet the needs of our customers' price and consumer target band, local tastes, regulations, etc.
		</p>

		<p>
		ASTERiSM JAPAN combines professional skills in the pharmaceutical sciences, engineering, design, business and law with GMP-certified factories based in Japan. Through ASTERiSM JAPAN Innovations, we also offer consulting services that encompass product formulation and licensing.
		</p>
	</div>
</div>

app/views/static_pages/all_users.html.erb
<h1>Users</h1>

<div class="table-responsive">
  <table class="table table-striped">
   
    <%########## Begin table headings #####################%>
    <thead>
      <tr>
        <th class="text-center">User ID</th>
        <th class="text-center">Last name</th>
        <th class="text-center">First name</th>
        <th class="text-center">Email</th>
        <th class="text-center">Company name</th>
        <th class="text-center">Company's city</th>
        <th class="text-center">Company's address</th>
        <th class="text-center">Company's country</th>
        <th class="text-center">Role</th>
        <th class="text-center">Edit</th>
      </tr>
    </thead>

    <%########### Begin table cells in rows ###########%>
    <% @users.each do |user| %> 
      <tr>
  			<ul>
          <td class="text-center"><%= user.id %></td>
					<td class="text-center"><%= user.last_name %></td>
					<td class="text-center"><%= user.first_name %></td>
					<td class="text-center"><%= user.email %></td>
					<td class="text-center"><%= user.company %></td>
					<td class="text-center"><%= user.office_city %></td>
					<td class="text-center"><%= user.office_location %></td>
					<td class="text-center"><%= user.office_country %></td>
          <td class="text-center"><% if user.admin == true %>
                                    <%= 'Admin' %>
                                  <% end %>
                                  <% if user.employee == true %>
                                    <%= 'Employee' %>
                                  <% end %>
                                  <% if user.customer == true %>
                                    <%= 'Customer' %>
                                  <% end %>
          </td>
          <td class="text-center"><%= link_to 'Edit', edit_user_path(user) %></td>
  			</ul>
  		</tr>
    <% end %>
	</table>
</div>

app/views/static_pages/command_center.html.erb
<h1>Command Center</h1>

<div class="row">
  <div class="panel panel-default col-md-4">
    <div class="panel-heading">
      <h4 class="panel-title big-font">
        <a data-toggle="collapse" data-parent="#accordion" href="#collapseOne">
          All Products
        </a>
      </h4>
    </div>
    <div id="collapseOne" class="panel-collapse collapse in">
      <div class="panel-body">
				<%= render 'small_product_list' %>
        <form method="" action="">
          <input id="new_a" type="hidden" name="a" value=<%= current_user.first_name.to_s %> ><br/>
          Product name (required):<br/>
          <input id="new_pn" type="text" name="pn" value="" required><br/><br/>
        </form>
        <button id="submit_pn" class="btn btn-primary">Create product</button>
      </div>
    </div>
  </div>
  <div class="panel panel-default col-md-4">
    <div class="panel-heading">
      <h4 class="panel-title big-font">
        <a data-toggle="collapse" data-parent="#accordion" href="#collapseTwo">
          All Users
        </a>
      </h4>
    </div>
    <div id="collapseTwo" class="panel-collapse collapse in">
      <div class="panel-body">
				<%= render 'small_user_list' %>
				<br/>
				<br/>
				<%= link_to "View full user list", all_users_path, class: "btn btn-primary" %>
      </div>
    </div>
  </div>
  <div class="panel panel-default col-md-4">
    <div class="panel-heading">
      <h4 class="panel-title big-font">
        <a data-toggle="collapse" data-parent="#accordion" href="#collapseThree">
          Assign Product to User
        </a>
      </h4>
    </div>
    <div id="collapseThree" class="panel-collapse collapse in">
      <div class="panel-body">
        <p>So you have have some products and some users! Make sure that you assign the product using the Product Key to a specific user by their User ID number. If you don't do this, your users won't see any products on their page.</p>
        <br/>
				<form method="" action="">
          Product Key (required):<br/> 
          <input id="grant_pk" type="text" cols="90" rows="5" name="pk" value="" required></input><br/><br/>
          User ID (required):<br/>
          <input id="grant_aid" type="text" name="aid" value="" required><br/><br/>
        </form>
        <br/>
        <button id="submit_grant" class="btn btn-primary">Assign Product to User</button>
        <br/>
        <br/>
        <button id="submit_revoke" class="btn btn-danger">Remove Product From User</button>
      </div>
    </div>
  </div>
  
</div>

app/views/static_pages/contact.html.erb
<h1>Contact</h1>


<div class="row">
  <div class="col-md-6 col-md-offset-3 well well-lg">
		<h4>Head Office</h4>
		<p>
			Sannomiya Venture Bldg 322 <br/>
			Chuo-Ku, Hamabe-Dori 4-1-23 <br/>
			Kobe 651-0083, JAPAN <br/>
			Tel: +81 (0) 78-200-5731<br/>
			Email: info@asterism-healthcareplus.com
		</p><br/>

		<h4>International Sales Office</h4>
		</p>
			Mumbai, INDIA<br/>
			Tel: +91-99201 24848<br/>
			Email: sales@asterism-healthcareplus.com
		</p><br/>
		<p>
			ASTERiSM Healthcare Plus (株）<br/>
			〒651-0083 <br/>
			兵庫県神戸市中央区浜辺通り４丁目１－２３<br/>
			三宮ベンチャービル３２２号室<br/>
			Tel: 078-200-5731
		</p>
	</div>
</div>

app/views/static_pages/home.html.erb
<div class="center hero-unit">
	<h1>Welcome to Asterism Healthcare Plus</h1>

	<h2>
		Your place for healthy drinks from Japan
	</h2>
	<% if false %>
	<%= link_to "Sign up now!", '#', class: "btn btn-large btn-primary" %>
	<% end %>
	<div class="row">
		<div class="col-md-4"></div>
		<div class="col-md-4">
			<p class="bg-danger">Please excuse our dust. Something awesome is coming soon!</p>
		</div>
		<div class="col-md-4"></div>
	</div>
</div>

app/views/static_pages/table_partials/_icon_button.html.erb
<% if @table_highlight == true %>
  <button type="button" class="btn btn-default no-button-border dropdown-toggle blink" data-toggle="dropdown">
    <%= @table_icon %>
    <% if @inside_panel == true %>
      <br/><%= @step %>
    <% end %>
  </button>
<% else %>
  <button type="button" class="btn btn-default no-button-border dropdown-toggle" data-toggle="dropdown">
    <%= @table_icon %>
    <% if @inside_panel == true %>
      <br/><%= @step %>
    <% end %>
  </button>
<% end %>

app/views/user/edit.html.erb
<h2>Edit <%= "#{@user.first_name}" + ' ' + "#{@user.last_name}" %></h2>


<%= simple_form_for(@user, :url => user_path, :html => { :method => :put }, :wrapper => :bootstrap3_horizontal, :html => { :class => 'form-horizontal' }) do |f| %>
  <%= f.error_notification %>

  <div class="row">
    <h4 class="col-sm-offset-4 col-sm-4">Account information</h4>
    <p class="col-sm-offset-4 col-sm-4">Sign in credentials</p>
  </div>
  <%= f.input :email, label_html: { class: 'col-sm-4' }, placeholder: 'yourname@example.com' %>
  <%= f.input :password, label: 'New password', label_html: { class: 'col-sm-4' } %>
  <%= f.input :password_confirmation, label: 'Confirm your new password', label_html: { class: 'col-sm-4' } %>
  <%= f.input :current_password, label_html: { class: 'col-sm-4' } %>
  <br/>

  <div class="row">
    <h4 class="col-sm-offset-4 col-sm-4">Personal information</h4>
    <p class="col-sm-offset-4 col-sm-4">Information about the individual</p>
  </div>
  <%= f.input :first_name, label: 'First Name', label_html: { class: 'col-sm-4' } %>
  <%= f.input :last_name, label: 'Last Name', label_html: { class: 'col-sm-4' } %>
  <br/>

  <div class="row">
    <h4 class="col-sm-offset-4 col-sm-4">Company information</h4>
    <p class="col-sm-offset-4 col-sm-4">Information about the company</p>
  </div>
  <%= f.input :company, label: 'Company name', label_html: { class: 'col-sm-4' } %>
  <%= f.input :office_country, label: 'Country', label_html: { class: 'col-sm-4' } %>
  <%= f.input :office_city, label: 'City', label_html: { class: 'col-sm-4' } %>
  <%= f.input :office_location, label: 'Address', label_html: { class: 'col-sm-4' } %>
  <br/>

  <div class="row">
    <h4 class="col-sm-offset-4 col-sm-4">Role</h4>
    <p class="col-sm-offset-4 col-sm-4">What is this individual's role? More than one role is permitted.</p>
  </div>
  <%= f.input :customer, label_html: { class: 'col-sm-4' } %>
  <%= f.input :employee, label_html: { class: 'col-sm-4' } %>
  <%= f.input :admin, label_html: { class: 'col-sm-4' } if current_user.admin? %><%# only admin can check/uncheck admin %>
  <br/>
  <br/>

  <%= f.submit "Update", class: 'btn btn-primary col-sm-offset-4' %>
<% end %>
<br/>

<h3>Cancel <%= "#{@user.first_name}" + ' ' + "#{@user.last_name}" + "'s account?" %></h3>

<%= button_to "Cancel account", @user, :data => { :confirm => "Are you sure?" }, :method => :delete %>

<%= link_to "Back", :back %>